jwtSecret: "test-jwt-secret-for-kind-cluster-min-32-chars!!"

courseService:
  image:
    repository: localhost/elearning-course-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8082
    nodePort: 30082

userService:
  image:
    repository: localhost/elearning-user-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8081
    nodePort: 30081

frontend:
  service:
    type: ClusterIP
    port: 3000

ingress:
  enabled: false

grafanaIngress:
  enabled: false

postgresql:
  enabled: false
  auth:
    username: elearning
    password: elearning_secret
    database: elearning
  primary:
    persistence:
      enabled: false
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    resources:
      requests: {}
      limits: {}

prometheus:
  enabled: false

grafana:
  enabled: false

serviceMonitor:
  enabled: false
