jwtSecret: "test-jwt-secret-for-kind-cluster-min-32-chars!!"

courseService:
  image:
    repository: localhost/elearning-course-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8082
    nodePort: 30082

userService:
  image:
    repository: localhost/elearning-user-service
    tag: latest
    pullPolicy: IfNotPresent
  env:
    CORS_ORIGINS: "http://localhost:3000,http://localhost:5173"
  service:
    type: NodePort
    port: 8081
    nodePort: 30081

frontend:
  image:
    repository: localhost/elearning-frontend
    tag: latest
    pullPolicy: IfNotPresent
  origin: "http://localhost:3000"
  service:
    type: NodePort
    port: 3000
    nodePort: 30080

sso:
  enabled: true
  redirectBase: "http://localhost:3000"
  providers:
    - id: github
      name: GitHub
      client_id: "Iv23lio9LgGJ8blbGG7e"
      client_secret: "c8465a66ca28b389a2810ff116f44c97a35b6ae9"

ldapService:
  enabled: false

ingress:
  enabled: false

grafanaIngress:
  enabled: false

postgresql:
  enabled: false
  auth:
    username: elearning
    password: elearning_secret
    database: elearning
  primary:
    persistence:
      enabled: false
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    resources:
      requests: {}
      limits: {}

prometheus:
  enabled: false

grafana:
  enabled: false

serviceMonitor:
  enabled: false
