jwtSecret: "test-jwt-secret-for-kind-cluster-min-32-chars!!"

courseService:
  image:
    repository: ghcr.io/towarmat83/elearning-course-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8082
    nodePort: 30082

userService:
  image:
    repository: ghcr.io/towarmat83/elearning-user-service
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8081
    nodePort: 30081

frontend:
  image:
    repository: ghcr.io/towarmat83/elearning-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 3000
    nodePort: 30080

sso:
  enabled: true
  redirectBase: "http://localhost:3000"
  providers:
    - id: github
      name: GitHub
      client_id: "Iv23lio9LgGJ8blbGG7e"
      client_secret: "c8465a66ca28b389a2810ff116f44c97a35b6ae9"

ingress:
  enabled: false

postgresql:
  enabled: true
  auth:
    username: elearning
    password: elearning_secret
    database: elearning
  persistence:
    enabled: false
