apiVersion: v1
kind: Secret
metadata:
  name: gitlab-keycloak-oidc
  namespace: gitlab
type: Opaque
stringData:
  # Must match the `secret` defined in realm-wks-main.yaml for the `gitlab` client
  client-secret: "gitlab-keycloak-dev-secret"
