[[permission]]
identifier = "allow-app-commands"
description = "Allow all Pupitre app commands"
commands.allow = [
    "local_check",
    "check_podman_images",
    "check_podman_lab2",
    "check_distrobox_lab3",
    "check_distrobox_lab3_container",
    "check_distrobox_lab3_install",
    "check_distrobox_lab3_export",
]
